# Generated by Django 4.2.16 on 2025-01-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaties', '0004_remove_article_pdf_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
